name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "."
        target: "/app/passOut2025"

    - name: Deploy on server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /app/passOut2025
          
          # Собираем образ на сервере
          docker build -t passout:latest .
          
          # Останавливаем и удаляем старый контейнер
          docker stop passout-app || true
          docker rm passout-app || true
          
          # Запускаем новый контейнер
          docker run -d \
            --name passout-app \
            --restart unless-stopped \
            -p 127.0.0.1:4000:4000 \
            -e TZ=Europe/Moscow \
            passout:latest
          
          # Очищаем старые образы
          docker image prune -f